# Generated by Django 4.2.27 on 2025-12-29 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='encryptedvote',
            name='signature',
            field=models.TextField(blank=True, null=True),
        ),
    ]
