# Generated by Django 4.2.27 on 2025-12-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(default='unknown', max_length=50)),
                ('last_checked', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
