# Generated by Django 4.2.27 on 2026-01-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_mfa_devices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mfatotpdevice',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mfatotpdevice',
            name='secret',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='webauthncredential',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
